version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: TestHeroBackendGo  # Default database created by PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: TestHeroBackendGo
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["go", "run", "main.go"]

networks:
  app-network:

volumes:
  postgres_data:
